# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/itolab/work/toma/MCL/PCL

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/itolab/work/toma/MCL/PCL

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/itolab/work/toma/MCL/PCL/CMakeFiles /home/itolab/work/toma/MCL/PCL/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/itolab/work/toma/MCL/PCL/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named PCL

# Build rule for target.
PCL: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 PCL
.PHONY : PCL

# fast build rule for target.
PCL/fast:
	$(MAKE) -f CMakeFiles/PCL.dir/build.make CMakeFiles/PCL.dir/build
.PHONY : PCL/fast

#=============================================================================
# Target rules for targets named fusion

# Build rule for target.
fusion: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fusion
.PHONY : fusion

# fast build rule for target.
fusion/fast:
	$(MAKE) -f CMakeFiles/fusion.dir/build.make CMakeFiles/fusion.dir/build
.PHONY : fusion/fast

#=============================================================================
# Target rules for targets named pcd_slide

# Build rule for target.
pcd_slide: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pcd_slide
.PHONY : pcd_slide

# fast build rule for target.
pcd_slide/fast:
	$(MAKE) -f CMakeFiles/pcd_slide.dir/build.make CMakeFiles/pcd_slide.dir/build
.PHONY : pcd_slide/fast

#=============================================================================
# Target rules for targets named pcd_turn

# Build rule for target.
pcd_turn: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pcd_turn
.PHONY : pcd_turn

# fast build rule for target.
pcd_turn/fast:
	$(MAKE) -f CMakeFiles/pcd_turn.dir/build.make CMakeFiles/pcd_turn.dir/build
.PHONY : pcd_turn/fast

#=============================================================================
# Target rules for targets named pcd_write

# Build rule for target.
pcd_write: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pcd_write
.PHONY : pcd_write

# fast build rule for target.
pcd_write/fast:
	$(MAKE) -f CMakeFiles/pcd_write.dir/build.make CMakeFiles/pcd_write.dir/build
.PHONY : pcd_write/fast

#=============================================================================
# Target rules for targets named registration

# Build rule for target.
registration: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 registration
.PHONY : registration

# fast build rule for target.
registration/fast:
	$(MAKE) -f CMakeFiles/registration.dir/build.make CMakeFiles/registration.dir/build
.PHONY : registration/fast

PCL.o: PCL.cpp.o
.PHONY : PCL.o

# target to build an object file
PCL.cpp.o:
	$(MAKE) -f CMakeFiles/PCL.dir/build.make CMakeFiles/PCL.dir/PCL.cpp.o
.PHONY : PCL.cpp.o

PCL.i: PCL.cpp.i
.PHONY : PCL.i

# target to preprocess a source file
PCL.cpp.i:
	$(MAKE) -f CMakeFiles/PCL.dir/build.make CMakeFiles/PCL.dir/PCL.cpp.i
.PHONY : PCL.cpp.i

PCL.s: PCL.cpp.s
.PHONY : PCL.s

# target to generate assembly for a file
PCL.cpp.s:
	$(MAKE) -f CMakeFiles/PCL.dir/build.make CMakeFiles/PCL.dir/PCL.cpp.s
.PHONY : PCL.cpp.s

fusion.o: fusion.cpp.o
.PHONY : fusion.o

# target to build an object file
fusion.cpp.o:
	$(MAKE) -f CMakeFiles/fusion.dir/build.make CMakeFiles/fusion.dir/fusion.cpp.o
.PHONY : fusion.cpp.o

fusion.i: fusion.cpp.i
.PHONY : fusion.i

# target to preprocess a source file
fusion.cpp.i:
	$(MAKE) -f CMakeFiles/fusion.dir/build.make CMakeFiles/fusion.dir/fusion.cpp.i
.PHONY : fusion.cpp.i

fusion.s: fusion.cpp.s
.PHONY : fusion.s

# target to generate assembly for a file
fusion.cpp.s:
	$(MAKE) -f CMakeFiles/fusion.dir/build.make CMakeFiles/fusion.dir/fusion.cpp.s
.PHONY : fusion.cpp.s

pcd_slide.o: pcd_slide.cpp.o
.PHONY : pcd_slide.o

# target to build an object file
pcd_slide.cpp.o:
	$(MAKE) -f CMakeFiles/pcd_slide.dir/build.make CMakeFiles/pcd_slide.dir/pcd_slide.cpp.o
.PHONY : pcd_slide.cpp.o

pcd_slide.i: pcd_slide.cpp.i
.PHONY : pcd_slide.i

# target to preprocess a source file
pcd_slide.cpp.i:
	$(MAKE) -f CMakeFiles/pcd_slide.dir/build.make CMakeFiles/pcd_slide.dir/pcd_slide.cpp.i
.PHONY : pcd_slide.cpp.i

pcd_slide.s: pcd_slide.cpp.s
.PHONY : pcd_slide.s

# target to generate assembly for a file
pcd_slide.cpp.s:
	$(MAKE) -f CMakeFiles/pcd_slide.dir/build.make CMakeFiles/pcd_slide.dir/pcd_slide.cpp.s
.PHONY : pcd_slide.cpp.s

pcd_turn.o: pcd_turn.cpp.o
.PHONY : pcd_turn.o

# target to build an object file
pcd_turn.cpp.o:
	$(MAKE) -f CMakeFiles/pcd_turn.dir/build.make CMakeFiles/pcd_turn.dir/pcd_turn.cpp.o
.PHONY : pcd_turn.cpp.o

pcd_turn.i: pcd_turn.cpp.i
.PHONY : pcd_turn.i

# target to preprocess a source file
pcd_turn.cpp.i:
	$(MAKE) -f CMakeFiles/pcd_turn.dir/build.make CMakeFiles/pcd_turn.dir/pcd_turn.cpp.i
.PHONY : pcd_turn.cpp.i

pcd_turn.s: pcd_turn.cpp.s
.PHONY : pcd_turn.s

# target to generate assembly for a file
pcd_turn.cpp.s:
	$(MAKE) -f CMakeFiles/pcd_turn.dir/build.make CMakeFiles/pcd_turn.dir/pcd_turn.cpp.s
.PHONY : pcd_turn.cpp.s

pcd_write.o: pcd_write.cpp.o
.PHONY : pcd_write.o

# target to build an object file
pcd_write.cpp.o:
	$(MAKE) -f CMakeFiles/pcd_write.dir/build.make CMakeFiles/pcd_write.dir/pcd_write.cpp.o
.PHONY : pcd_write.cpp.o

pcd_write.i: pcd_write.cpp.i
.PHONY : pcd_write.i

# target to preprocess a source file
pcd_write.cpp.i:
	$(MAKE) -f CMakeFiles/pcd_write.dir/build.make CMakeFiles/pcd_write.dir/pcd_write.cpp.i
.PHONY : pcd_write.cpp.i

pcd_write.s: pcd_write.cpp.s
.PHONY : pcd_write.s

# target to generate assembly for a file
pcd_write.cpp.s:
	$(MAKE) -f CMakeFiles/pcd_write.dir/build.make CMakeFiles/pcd_write.dir/pcd_write.cpp.s
.PHONY : pcd_write.cpp.s

registration.o: registration.cpp.o
.PHONY : registration.o

# target to build an object file
registration.cpp.o:
	$(MAKE) -f CMakeFiles/registration.dir/build.make CMakeFiles/registration.dir/registration.cpp.o
.PHONY : registration.cpp.o

registration.i: registration.cpp.i
.PHONY : registration.i

# target to preprocess a source file
registration.cpp.i:
	$(MAKE) -f CMakeFiles/registration.dir/build.make CMakeFiles/registration.dir/registration.cpp.i
.PHONY : registration.cpp.i

registration.s: registration.cpp.s
.PHONY : registration.s

# target to generate assembly for a file
registration.cpp.s:
	$(MAKE) -f CMakeFiles/registration.dir/build.make CMakeFiles/registration.dir/registration.cpp.s
.PHONY : registration.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... PCL"
	@echo "... edit_cache"
	@echo "... fusion"
	@echo "... pcd_slide"
	@echo "... pcd_turn"
	@echo "... pcd_write"
	@echo "... rebuild_cache"
	@echo "... registration"
	@echo "... PCL.o"
	@echo "... PCL.i"
	@echo "... PCL.s"
	@echo "... fusion.o"
	@echo "... fusion.i"
	@echo "... fusion.s"
	@echo "... pcd_slide.o"
	@echo "... pcd_slide.i"
	@echo "... pcd_slide.s"
	@echo "... pcd_turn.o"
	@echo "... pcd_turn.i"
	@echo "... pcd_turn.s"
	@echo "... pcd_write.o"
	@echo "... pcd_write.i"
	@echo "... pcd_write.s"
	@echo "... registration.o"
	@echo "... registration.i"
	@echo "... registration.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

